services:
  database:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: audit_trail_test
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3337:3306"
    volumes:
      - db_data_test:/var/lib/mysql

volumes:
  db_data_test:
