AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java17
      Handler: gap.aws.functions.App::handleRequest
      Timeout: 60
      MemorySize: 512
      CodeUri: ./target/aws-create-user.jar